version: "3.9"

services:
  mongo-db:
    image: "mongo:4.4"
    restart: always
    ports: 
        - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongo-db
    ports:
      - '8080:8081'
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo-db:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

volumes: 
  mongodb_data:
  mongodb_config: